version: '3.8'

services:
  generator:
    image: ghcr.io/aloshy-ai/deep-job-seek:latest
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-BAAI/bge-small-en-v1.5}
      DOCKER_ENV: "true"
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped

  qdrant:
    image: ghcr.io/aloshy-ai/deep-job-seek:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/localhost/6333) &>/dev/null"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  qdrant_data: